# Pre-req: source <ISE_DS_install_dir>/settings64.sh

DEVICE=xc6vlx240t-ff1156-1


### Misc ###
clean:
	rm -rf *.lst *.bld *.xrpt *.ngm *.xml *.mrp *.map *.html *.ptwx *.csv *.pad *.txt *.unroutes *.xpi *.tw* *.log
	rm -rf *.ngd *.ngc *.pcf *.ncd *.par *.his
	rm -rf xlnx_* _xmsgs xst
	rm -rf *.drc *.bit *.xwbt *.bgn
	rm -rf *.prm *.psr *.cfi *.en *.bin *.pwr *.lso *.syr

cleansyn:
	rm -rf *.log *.xrpt *.ngc
	rm -rf xst _xmsgs

