# Pre-req: source <ISE_DS_install_dir>/settings64.sh

DEVICE=xc6vlx240t-ff1156-1


all:
	xtclsh SDI_DEMO3.tcl rebuild_project

clean:
	rm -rf *.lst *.bld *.xrpt *.ngm *.xml *.mrp *.map *.html *.ptwx *.csv *.pad *.txt *.unroutes *.xpi *.tw* *.log
	rm -rf *.ngd *.ngc *.pcf *.ncd *.par *.his xlnx_* _xmsgs xst _ngo *.xise *.ngr *.xst *.stx *.ut *.gise
	rm -rf *.drc *.bit *.xwbt *.bgn *.cmd_log *.prj
	rm -rf *.prm *.psr *.cfi *.en *.bin *.pwr *.lso *.syr

