/*@ begin PerfTuning (  
 def build { 
   arg build_command = 'icc -O3 -openmp -lm -I/disks/fast/papi/include -L/disks/fast/papi/lib -lpapi';
 }

 def performance_counter {
   arg repetitions = 100;
 }

 def performance_params {
   param UNROLL_FAC_OUT[] = [1,2,3,4];
   param UNROLL_FAC_IN[] = [1,2,3,4,5,6,7,8];
   param N_THREADS[] = [1];
   param SIMD_TYPE[] = ['none','sse'];
   param BLK_TYPE[] = ['inode'];

   constraint simd_unroll_factor = (SIMD_TYPE=='none' or UNROLL_FAC_IN%2==0);
 }

 def input_params {
   param G_NROWS[] = [260100];
   param G_NCOLS[] = [260100];
   param B_NROWS[] = [4];
   param B_NCOLS_MIN[] = [12];
   param B_NCOLS_MAX[] = [20];
   param B_NCOLS_STRIDE[] = [4];

   constraint square_x_y = (G_NROWS==G_NCOLS);
 }
 
 def input_vars { 
   arg decl_file = 'decl_code.h';
   arg init_file = 'init_code.c'; 
 } 
 
 def performance_test_code { 
   arg skeleton_code_file = 'skeleton_code.c';  
 } 

 def search
 {
   arg algorithm = 'Exhaustive';
 }  
 ) @*/

/**-- (Generated by Orio) 
Best performance cost: 
  43771092.000000 
Tuned for specific problem sizes: 
  B_NCOLS_MAX = 20 
  B_NCOLS_MIN = 12 
  B_NCOLS_STRIDE = 4 
  B_NROWS = 4 
  G_NCOLS = 260100 
  G_NROWS = 260100 
Best performance parameters: 
  BLK_TYPE = inode 
  N_THREADS = 1 
  SIMD_TYPE = sse 
  UNROLL_FAC_IN = 4 
  UNROLL_FAC_OUT = 1 
--**/

 

/*@ begin SpMV (
  # SpMV computation: y = y + aa * x;
  out_vector = y;
  in_vector = x;
  in_matrix = aa;
  row_inds = ai;
  col_inds = aj;
  data_type = double;
  init_val = 0;
  total_rows = total_rows;       
  total_inodes = total_inodes;   
  inode_sizes = inode_sizes;     
  inode_rows = inode_rows;       
  
  # transformation parameters
  out_unroll_factor = UNROLL_FAC_OUT;
  in_unroll_factor = UNROLL_FAC_IN;
  num_threads = N_THREADS;
  simd = SIMD_TYPE;              # 'none' (default), 'gcc', 'sse', 'xlc'
  block_structure = BLK_TYPE;    # 'none' (default), 'inode', 'bcsr' (still unsupported)
  ) @*/
{

  double tbuf[2];
  register int n=total_inodes;
  while (n--) {
    register int rlength=inode_sizes[0]; inode_sizes+=1;
    register int clength=ai[1]-ai[0]; ai+=rlength;
    register int i=0;
    while (i<=rlength-1) {
      __m128d y0v=_mm_set1_pd(0);
      register int j=0;
      while (j<=clength-4) {
        __m128d x0v=_mm_setr_pd(x[aj[0]],x[aj[1]]),x1v=_mm_setr_pd(x[aj[2]],x[aj[3]]);
        __m128d aav0=_mm_load_pd(&aa[0]),aav1=_mm_load_pd(&aa[2]);
        y0v=_mm_add_pd(y0v,_mm_mul_pd(aav0,x0v));
        y0v=_mm_add_pd(y0v,_mm_mul_pd(aav1,x1v));
        aa+=4;
        aj+=4;
        j+=4;
      }
      _mm_storer_pd(&tbuf[0],y0v);
      double y0=tbuf[0]+tbuf[1];
      while (j<=clength-1) {
        y0 += aa[0]*x[aj[0]];
        aa+=1;
        aj+=1;
        j+=1;
      }
      y[0]=y0;
      y+=1;
      i+=1;
    }
  }
  
}
/*@ end @*/

/*@ end @*/

