DIMENSION      04
BB_EXE         m_matvec.c.nomad.obj.exe
BB_INPUT_TYPE  ( I I B I )
BB_OUTPUT_TYPE OBJ CNT_EVAL 
X0             ( 0 0 0 0 )
LOWER_BOUND    ( 0 0 0 0 )
UPPER_BOUND    ( 8 8 1 3 )
MAX_BB_EVAL    1000
DISPLAY_STATS  BBE OBJ EVAL
SEED    1
