#include <stdio.h>
#include <stdlib.h>
#include <sys/time.h>
#include <math.h>

double A[N][N+13];

void init_arrays()
{
  int i, j;
  for (i=0; i<N; i++) 
    for (j=0; j<N; j++) 
      A[i][j] = i*i+j*j;
}

double rtclock()
{
  struct timezone tzp;
  struct timeval tp;
  int stat;
  gettimeofday (&tp, &tzp);
  return (tp.tv_sec + tp.tv_usec*1.0e-6);
}

int main()
{
  init_arrays();

  double annot_t_start=0, annot_t_end=0, annot_t_total=0;
  int annot_i;

  for (annot_i=0; annot_i<REPS; annot_i++)
  {
    annot_t_start = rtclock();
    

/*@ begin PerfTuning (          
  def build  
  {  
    arg build_command = 'icc -O3 -openmp -lm';  
  }
     
  def performance_counter           
  {  
    arg repetitions = 1;  
  } 
 
  def performance_params  
  { 
# [1,8,16,32,64,128,256]; 
# [1,4,8,16,32];

    param T1_1[] = [32];
    param T1_2[] = [32];
    param T1_3[] = [32];
    param T2_1[] = [1];
    param T2_2[] = [1];
    param T2_3[] = [1];
 
    constraint c1 = (T1_1*T2_1<=1024 and T1_1*T2_1<=1024 and T1_1*T2_1<=1024);

    param U1[] = [1];
    param U2[] = [4,8];
    param U3[] = [4,8];

    constraint c2 = (U1*U2*U3<=256);

    param PERM[] = [
     [0,1,2],
#     [0,2,1],
#     [1,0,2],
#     [1,2,0],
#     [2,0,1],
#     [2,1,0],
    ];

    param PAR[] = [True];
    param SCREP[] = [False];
    param IVEC[] = [False];
    param RECTILE[] = [True,False];
  } 
 
  def search  
  {
    arg algorithm = 'Exhaustive';  
#    arg algorithm = 'Simplex';  
#    arg total_runs = 1; 
  }

  def input_params  
  {
    param T[] = [500];
    param N[] = [4000];
  } 

  def input_vars
  {
    decl static double A[N][N+17] = random;
  }
) @*/

/**-- (Generated by Orio) 
Best performance cost: 
  7.561850 
Tuned for specific problem sizes: 
  N = 4000 
  T = 500 
Best performance parameters: 
  IVEC = False 
  PAR = True 
  PERM = [0, 1, 2] 
  RECTILE = True 
  SCREP = False 
  T1_1 = 32 
  T1_2 = 32 
  T1_3 = 32 
  T2_1 = 1 
  T2_2 = 1 
  T2_3 = 1 
  U1 = 1 
  U2 = 4 
  U3 = 4 
--**/

  

register int i,j,k,t; 
register int c1t, c2t, c3t, c4t, c5t, c6t, c7t, c8t, c9t, c10t, c11t, c12t; 
register int newlb_c1, newlb_c2, newlb_c3, newlb_c4, newlb_c5, newlb_c6, 
  newlb_c7, newlb_c8, newlb_c9, newlb_c10, newlb_c11, newlb_c12; 
register int newub_c1, newub_c2, newub_c3, newub_c4, newub_c5, newub_c6, 
  newub_c7, newub_c8, newub_c9, newub_c10, newub_c11, newub_c12; 

/*@ begin PolySyn( 
  parallel = PAR;
  tiles = [T1_1,T1_2,T1_3,T2_1,T2_2,T2_3];
  permut = PERM;
  unroll_factors = [U1,U2,U3];
  rect_regtile = RECTILE;
  scalar_replace = SCREP;
  vectorize = IVEC;

  profiling_code = 'seidel_profiling.c';
  compile_cmd = 'gcc';
  compile_opts = '-lm';
) @*/#include <math.h>
#include <assert.h>
#include <omp.h>
#define ceild(n,d)  ceil(((double)(n))/((double)(d)))
#define floord(n,d) floor(((double)(n))/((double)(d)))
#define max(x,y)    ((x) > (y)? (x) : (y))
#define min(x,y)    ((x) < (y)? (x) : (y))




 int c1, c2, c3, c4, c5, c6, c7, c8, c9;
 register int lb, ub, lb1, ub1, lb2, ub2;
/* polysyn start */
if (N >= 3) {
  for (c1=-1;c1<=floord(2*T+N-4,32);c1++) {
 lb1=max(max(ceild(16*c1-15,32),0),ceild(32*c1-T+1,32));
 ub1=min(min(floord(32*c1+31,32),floord(T+N-3,32)),floord(32*c1+N+29,64));
#pragma omp parallel for shared(c1,lb1,ub1) private(c2,c3,c4,c5,c6,c7,c8,c9)
 for (c2=lb1; c2<=ub1; c2++) {
/*@ begin Loop(
transform Composite(
permut = [['c7', 'c8', 'c9']],
  unrolljam = (['c7', 'c8', 'c9'],[1, 4, 4]),
  scalarreplace = (False, 'double'))

      for (c3=max(max(max(max(ceild(64*c1-64*c2-29,32),0),ceild(64*c2-N-28,32)),ceild(16*c2-15,16)),ceild(16*c1-15,16));c3<=min(min(min(min(floord(T+N-3,16),floord(32*c1-32*c2+N+29,16)),floord(32*c1+N+60,32)),floord(32*c2+T+N+28,32)),floord(64*c2+N+59,32));c3++) {
        for (c7=max(max(max(max(0,32*c1-32*c2),16*c3-N+2),32*c2-N+2),-32*c2+32*c3-N-29);c7<=min(min(min(min(T-1,32*c1-32*c2+31),32*c2+30),floord(32*c3+29,2)),-32*c2+32*c3+30);c7++) {
          for (c8=max(max(32*c2,c7+1),32*c3-c7-N+2);c8<=min(min(32*c2+31,c7+N-2),32*c3-c7+30);c8++) {
            for (c9=max(32*c3,c7+c8+1);c9<=min(32*c3+31,c7+c8+N-2);c9++) {
              A[-c7+c8][-c7-c8+c9]=(A[1+-c7+c8][1+-c7-c8+c9]+A[1+-c7+c8][-c7-c8+c9]+A[1+-c7+c8][-c7-c8+c9-1]+A[-c7+c8][1+-c7-c8+c9]+A[-c7+c8][-c7-c8+c9]+A[-c7+c8][-c7-c8+c9-1]+A[-c7+c8-1][1+-c7-c8+c9]+A[-c7+c8-1][-c7-c8+c9]+A[-c7+c8-1][-c7-c8+c9-1])/9;
            }
          }
        }
      }

) @*/for (c3=max(max(max(max(ceild(64*c1-64*c2-29,32),0),ceild(64*c2-N-28,32)),ceild(16*c2-15,16)),ceild(16*c1-15,16)); c3<=min(min(min(min(floord(T+N-3,16),floord(32*c1-32*c2+N+29,16)),floord(32*c1+N+60,32)),floord(32*c2+T+N+28,32)),floord(64*c2+N+59,32)); c3++ ) {
  for (c7=max(max(max(max(0,32*c1-32*c2),16*c3-N+2),32*c2-N+2),-32*c2+32*c3-N-29); c7<=min(min(min(min(T-1,32*c1-32*c2+31),32*c2+30),floord(32*c3+29,2)),-32*c2+32*c3+30); c7++ ) {
    {
      for (c8=max(max(32*c2,c7+1),32*c3-c7-N+2); c8<=min(min(32*c2+31,c7+N-2),32*c3-c7+30)-3; c8=c8+4) {
        {
          for (c9=max(32*c3,c7+c8+1); c9<=min(32*c3+31,c7+c8+N-2)-3; c9=c9+4) {
            A[-c7+c8][-c7+c9-c8]=0.111111111111*(A[-c7+c8+1][-c7+c9-c8+1]+A[-c7+c8+1][-c7+c9-c8]+A[-c7+c8+1][-c7+c9-c8-1]+A[-c7+c8][-c7+c9-c8+1]+A[-c7+c8][-c7+c9-c8]+A[-c7+c8][-c7+c9-c8-1]+A[-c7+c8-1][-c7+c9-c8+1]+A[-c7+c8-1][-c7+c9-c8]+A[-c7+c8-1][-c7+c9-c8-1]);
            A[-c7+c8][-c7+c9-c8+1]=0.111111111111*(A[-c7+c8+1][-c7+c9-c8+2]+A[-c7+c8+1][-c7+c9-c8+1]+A[-c7+c8+1][-c7+c9-c8]+A[-c7+c8][-c7+c9-c8+2]+A[-c7+c8][-c7+c9-c8+1]+A[-c7+c8][-c7+c9-c8]+A[-c7+c8-1][-c7+c9-c8+2]+A[-c7+c8-1][-c7+c9-c8+1]+A[-c7+c8-1][-c7+c9-c8]);
            A[-c7+c8][-c7+c9-c8+2]=0.111111111111*(A[-c7+c8+1][-c7+c9-c8+3]+A[-c7+c8+1][-c7+c9-c8+2]+A[-c7+c8+1][-c7+c9-c8+1]+A[-c7+c8][-c7+c9-c8+3]+A[-c7+c8][-c7+c9-c8+2]+A[-c7+c8][-c7+c9-c8+1]+A[-c7+c8-1][-c7+c9-c8+3]+A[-c7+c8-1][-c7+c9-c8+2]+A[-c7+c8-1][-c7+c9-c8+1]);
            A[-c7+c8][-c7+c9-c8+3]=0.111111111111*(A[-c7+c8+1][-c7+c9-c8+4]+A[-c7+c8+1][-c7+c9-c8+3]+A[-c7+c8+1][-c7+c9-c8+2]+A[-c7+c8][-c7+c9-c8+4]+A[-c7+c8][-c7+c9-c8+3]+A[-c7+c8][-c7+c9-c8+2]+A[-c7+c8-1][-c7+c9-c8+4]+A[-c7+c8-1][-c7+c9-c8+3]+A[-c7+c8-1][-c7+c9-c8+2]);
          }
          for (; c9<=min(32*c3+31,c7+c8+N-2); c9=c9+1) {
            A[-c7+c8][-c7+c9-c8]=0.111111111111*(A[-c7+c8+1][-c7+c9-c8+1]+A[-c7+c8+1][-c7+c9-c8]+A[-c7+c8+1][-c7+c9-c8-1]+A[-c7+c8][-c7+c9-c8+1]+A[-c7+c8][-c7+c9-c8]+A[-c7+c8][-c7+c9-c8-1]+A[-c7+c8-1][-c7+c9-c8+1]+A[-c7+c8-1][-c7+c9-c8]+A[-c7+c8-1][-c7+c9-c8-1]);
          }
        }
        {
          for (c9=max(32*c3,c7+c8+2); c9<=min(32*c3+31,c7+c8+N-1)-3; c9=c9+4) {
            A[-c7+c8+1][-c7+c9-c8-1]=0.111111111111*(A[-c7+c8+2][-c7+c9-c8]+A[-c7+c8+2][-c7+c9-c8-1]+A[-c7+c8+2][-c7+c9-c8-2]+A[-c7+c8+1][-c7+c9-c8]+A[-c7+c8+1][-c7+c9-c8-1]+A[-c7+c8+1][-c7+c9-c8-2]+A[-c7+c8][-c7+c9-c8]+A[-c7+c8][-c7+c9-c8-1]+A[-c7+c8][-c7+c9-c8-2]);
            A[-c7+c8+1][-c7+c9-c8]=0.111111111111*(A[-c7+c8+2][-c7+c9-c8+1]+A[-c7+c8+2][-c7+c9-c8]+A[-c7+c8+2][-c7+c9-c8-1]+A[-c7+c8+1][-c7+c9-c8+1]+A[-c7+c8+1][-c7+c9-c8]+A[-c7+c8+1][-c7+c9-c8-1]+A[-c7+c8][-c7+c9-c8+1]+A[-c7+c8][-c7+c9-c8]+A[-c7+c8][-c7+c9-c8-1]);
            A[-c7+c8+1][-c7+c9-c8+1]=0.111111111111*(A[-c7+c8+2][-c7+c9-c8+2]+A[-c7+c8+2][-c7+c9-c8+1]+A[-c7+c8+2][-c7+c9-c8]+A[-c7+c8+1][-c7+c9-c8+2]+A[-c7+c8+1][-c7+c9-c8+1]+A[-c7+c8+1][-c7+c9-c8]+A[-c7+c8][-c7+c9-c8+2]+A[-c7+c8][-c7+c9-c8+1]+A[-c7+c8][-c7+c9-c8]);
            A[-c7+c8+1][-c7+c9-c8+2]=0.111111111111*(A[-c7+c8+2][-c7+c9-c8+3]+A[-c7+c8+2][-c7+c9-c8+2]+A[-c7+c8+2][-c7+c9-c8+1]+A[-c7+c8+1][-c7+c9-c8+3]+A[-c7+c8+1][-c7+c9-c8+2]+A[-c7+c8+1][-c7+c9-c8+1]+A[-c7+c8][-c7+c9-c8+3]+A[-c7+c8][-c7+c9-c8+2]+A[-c7+c8][-c7+c9-c8+1]);
          }
          for (; c9<=min(32*c3+31,c7+c8+N-1); c9=c9+1) {
            A[-c7+c8+1][-c7+c9-c8-1]=0.111111111111*(A[-c7+c8+2][-c7+c9-c8]+A[-c7+c8+2][-c7+c9-c8-1]+A[-c7+c8+2][-c7+c9-c8-2]+A[-c7+c8+1][-c7+c9-c8]+A[-c7+c8+1][-c7+c9-c8-1]+A[-c7+c8+1][-c7+c9-c8-2]+A[-c7+c8][-c7+c9-c8]+A[-c7+c8][-c7+c9-c8-1]+A[-c7+c8][-c7+c9-c8-2]);
          }
        }
        {
          for (c9=max(32*c3,c7+c8+3); c9<=min(32*c3+31,c7+c8+N)-3; c9=c9+4) {
            A[-c7+c8+2][-c7+c9-c8-2]=0.111111111111*(A[-c7+c8+3][-c7+c9-c8-1]+A[-c7+c8+3][-c7+c9-c8-2]+A[-c7+c8+3][-c7+c9-c8-3]+A[-c7+c8+2][-c7+c9-c8-1]+A[-c7+c8+2][-c7+c9-c8-2]+A[-c7+c8+2][-c7+c9-c8-3]+A[-c7+c8+1][-c7+c9-c8-1]+A[-c7+c8+1][-c7+c9-c8-2]+A[-c7+c8+1][-c7+c9-c8-3]);
            A[-c7+c8+2][-c7+c9-c8-1]=0.111111111111*(A[-c7+c8+3][-c7+c9-c8]+A[-c7+c8+3][-c7+c9-c8-1]+A[-c7+c8+3][-c7+c9-c8-2]+A[-c7+c8+2][-c7+c9-c8]+A[-c7+c8+2][-c7+c9-c8-1]+A[-c7+c8+2][-c7+c9-c8-2]+A[-c7+c8+1][-c7+c9-c8]+A[-c7+c8+1][-c7+c9-c8-1]+A[-c7+c8+1][-c7+c9-c8-2]);
            A[-c7+c8+2][-c7+c9-c8]=0.111111111111*(A[-c7+c8+3][-c7+c9-c8+1]+A[-c7+c8+3][-c7+c9-c8]+A[-c7+c8+3][-c7+c9-c8-1]+A[-c7+c8+2][-c7+c9-c8+1]+A[-c7+c8+2][-c7+c9-c8]+A[-c7+c8+2][-c7+c9-c8-1]+A[-c7+c8+1][-c7+c9-c8+1]+A[-c7+c8+1][-c7+c9-c8]+A[-c7+c8+1][-c7+c9-c8-1]);
            A[-c7+c8+2][-c7+c9-c8+1]=0.111111111111*(A[-c7+c8+3][-c7+c9-c8+2]+A[-c7+c8+3][-c7+c9-c8+1]+A[-c7+c8+3][-c7+c9-c8]+A[-c7+c8+2][-c7+c9-c8+2]+A[-c7+c8+2][-c7+c9-c8+1]+A[-c7+c8+2][-c7+c9-c8]+A[-c7+c8+1][-c7+c9-c8+2]+A[-c7+c8+1][-c7+c9-c8+1]+A[-c7+c8+1][-c7+c9-c8]);
          }
          for (; c9<=min(32*c3+31,c7+c8+N); c9=c9+1) {
            A[-c7+c8+2][-c7+c9-c8-2]=0.111111111111*(A[-c7+c8+3][-c7+c9-c8-1]+A[-c7+c8+3][-c7+c9-c8-2]+A[-c7+c8+3][-c7+c9-c8-3]+A[-c7+c8+2][-c7+c9-c8-1]+A[-c7+c8+2][-c7+c9-c8-2]+A[-c7+c8+2][-c7+c9-c8-3]+A[-c7+c8+1][-c7+c9-c8-1]+A[-c7+c8+1][-c7+c9-c8-2]+A[-c7+c8+1][-c7+c9-c8-3]);
          }
        }
        {
          for (c9=max(32*c3,c7+c8+4); c9<=min(32*c3+31,c7+c8+N+1)-3; c9=c9+4) {
            A[-c7+c8+3][-c7+c9-c8-3]=0.111111111111*(A[-c7+c8+4][-c7+c9-c8-2]+A[-c7+c8+4][-c7+c9-c8-3]+A[-c7+c8+4][-c7+c9-c8-4]+A[-c7+c8+3][-c7+c9-c8-2]+A[-c7+c8+3][-c7+c9-c8-3]+A[-c7+c8+3][-c7+c9-c8-4]+A[-c7+c8+2][-c7+c9-c8-2]+A[-c7+c8+2][-c7+c9-c8-3]+A[-c7+c8+2][-c7+c9-c8-4]);
            A[-c7+c8+3][-c7+c9-c8-2]=0.111111111111*(A[-c7+c8+4][-c7+c9-c8-1]+A[-c7+c8+4][-c7+c9-c8-2]+A[-c7+c8+4][-c7+c9-c8-3]+A[-c7+c8+3][-c7+c9-c8-1]+A[-c7+c8+3][-c7+c9-c8-2]+A[-c7+c8+3][-c7+c9-c8-3]+A[-c7+c8+2][-c7+c9-c8-1]+A[-c7+c8+2][-c7+c9-c8-2]+A[-c7+c8+2][-c7+c9-c8-3]);
            A[-c7+c8+3][-c7+c9-c8-1]=0.111111111111*(A[-c7+c8+4][-c7+c9-c8]+A[-c7+c8+4][-c7+c9-c8-1]+A[-c7+c8+4][-c7+c9-c8-2]+A[-c7+c8+3][-c7+c9-c8]+A[-c7+c8+3][-c7+c9-c8-1]+A[-c7+c8+3][-c7+c9-c8-2]+A[-c7+c8+2][-c7+c9-c8]+A[-c7+c8+2][-c7+c9-c8-1]+A[-c7+c8+2][-c7+c9-c8-2]);
            A[-c7+c8+3][-c7+c9-c8]=0.111111111111*(A[-c7+c8+4][-c7+c9-c8+1]+A[-c7+c8+4][-c7+c9-c8]+A[-c7+c8+4][-c7+c9-c8-1]+A[-c7+c8+3][-c7+c9-c8+1]+A[-c7+c8+3][-c7+c9-c8]+A[-c7+c8+3][-c7+c9-c8-1]+A[-c7+c8+2][-c7+c9-c8+1]+A[-c7+c8+2][-c7+c9-c8]+A[-c7+c8+2][-c7+c9-c8-1]);
          }
          for (; c9<=min(32*c3+31,c7+c8+N+1); c9=c9+1) {
            A[-c7+c8+3][-c7+c9-c8-3]=0.111111111111*(A[-c7+c8+4][-c7+c9-c8-2]+A[-c7+c8+4][-c7+c9-c8-3]+A[-c7+c8+4][-c7+c9-c8-4]+A[-c7+c8+3][-c7+c9-c8-2]+A[-c7+c8+3][-c7+c9-c8-3]+A[-c7+c8+3][-c7+c9-c8-4]+A[-c7+c8+2][-c7+c9-c8-2]+A[-c7+c8+2][-c7+c9-c8-3]+A[-c7+c8+2][-c7+c9-c8-4]);
          }
        }
      }
      for (; c8<=min(min(32*c2+31,c7+N-2),32*c3-c7+30); c8=c8+1) {
        {
          for (c9=max(32*c3,c7+c8+1); c9<=min(32*c3+31,c7+c8+N-2)-3; c9=c9+4) {
            A[-c7+c8][-c7+c9-c8]=0.111111111111*(A[-c7+c8+1][-c7+c9-c8+1]+A[-c7+c8+1][-c7+c9-c8]+A[-c7+c8+1][-c7+c9-c8-1]+A[-c7+c8][-c7+c9-c8+1]+A[-c7+c8][-c7+c9-c8]+A[-c7+c8][-c7+c9-c8-1]+A[-c7+c8-1][-c7+c9-c8+1]+A[-c7+c8-1][-c7+c9-c8]+A[-c7+c8-1][-c7+c9-c8-1]);
            A[-c7+c8][-c7+c9-c8+1]=0.111111111111*(A[-c7+c8+1][-c7+c9-c8+2]+A[-c7+c8+1][-c7+c9-c8+1]+A[-c7+c8+1][-c7+c9-c8]+A[-c7+c8][-c7+c9-c8+2]+A[-c7+c8][-c7+c9-c8+1]+A[-c7+c8][-c7+c9-c8]+A[-c7+c8-1][-c7+c9-c8+2]+A[-c7+c8-1][-c7+c9-c8+1]+A[-c7+c8-1][-c7+c9-c8]);
            A[-c7+c8][-c7+c9-c8+2]=0.111111111111*(A[-c7+c8+1][-c7+c9-c8+3]+A[-c7+c8+1][-c7+c9-c8+2]+A[-c7+c8+1][-c7+c9-c8+1]+A[-c7+c8][-c7+c9-c8+3]+A[-c7+c8][-c7+c9-c8+2]+A[-c7+c8][-c7+c9-c8+1]+A[-c7+c8-1][-c7+c9-c8+3]+A[-c7+c8-1][-c7+c9-c8+2]+A[-c7+c8-1][-c7+c9-c8+1]);
            A[-c7+c8][-c7+c9-c8+3]=0.111111111111*(A[-c7+c8+1][-c7+c9-c8+4]+A[-c7+c8+1][-c7+c9-c8+3]+A[-c7+c8+1][-c7+c9-c8+2]+A[-c7+c8][-c7+c9-c8+4]+A[-c7+c8][-c7+c9-c8+3]+A[-c7+c8][-c7+c9-c8+2]+A[-c7+c8-1][-c7+c9-c8+4]+A[-c7+c8-1][-c7+c9-c8+3]+A[-c7+c8-1][-c7+c9-c8+2]);
          }
          for (; c9<=min(32*c3+31,c7+c8+N-2); c9=c9+1) {
            A[-c7+c8][-c7-c8+c9]=(A[1+-c7+c8][1+-c7-c8+c9]+A[1+-c7+c8][-c7-c8+c9]+A[1+-c7+c8][-c7-c8+c9-1]+A[-c7+c8][1+-c7-c8+c9]+A[-c7+c8][-c7-c8+c9]+A[-c7+c8][-c7-c8+c9-1]+A[-c7+c8-1][1+-c7-c8+c9]+A[-c7+c8-1][-c7-c8+c9]+A[-c7+c8-1][-c7-c8+c9-1])/9;
          }
        }
      }
    }
  }
}
/*@ end @*/

    }
  }
}
/* polysyn end */

/*@ end @*/ 
/*@ end @*/ 



    annot_t_end = rtclock();
    annot_t_total += annot_t_end - annot_t_start;
  }
  
  annot_t_total = annot_t_total / REPS;

#ifndef TEST
  printf("%f\n", annot_t_total);
#else
  {
    int i, j;
    for (i=0; i<N; i++) {
      for (j=0; j<N; j++) {
	if (j%100==0)
	  printf("\n");
	printf("%f ",A[i][j]);
      }
      printf("\n");
    }
  }
#endif
  
  return ((int) A[0][0]); 

}
                                    
