/*@ begin PerfTuning (
 def build {
   arg build_command = 'gcc -O3';
   #arg libs = '-lrt';
 } 
 def performance_counter {
   #arg method = 'bgp counter';
   arg repetitions = 3;
 }
 def performance_params {  
   param UF[] = range(1,11);
   param VEC[] = [False,True];
   #constraint divisible_by_two = (UF % 2 == 0);
 }
 def input_params {
   param N[] = [100000];
 }
 def input_vars {
   decl dynamic double x1[N] = random;
   decl dynamic double x2[N] = random;
   decl dynamic double x3[N] = random;
   decl dynamic double x4[N] = random;
   decl dynamic double x5[N] = random;
   decl dynamic double y[N] = 0;
   decl double a1 = random;
   decl double a2 = random;
   decl double a3 = random;
   decl double a4 = random;
   decl double a5 = random;
 }
 def search {
   arg algorithm = 'Exhaustive';
 }
) 
@*/
/**-- (Generated by Orio) 
Best performance cost: 
  [0.000782013, 0.000673056, 0.000663042] 
Tuned for specific problem sizes: 
  N = 100000 
Best performance parameters: 
  UF = 5 
  VEC = True 
--**/



register int i;

/*@ begin Loop ( 
    transform Composite(
      unrolljam = (['i'],[UF]),
      vector = (VEC, ['ivdep','vector always'])
     )
  for (i=0; i<=N-1; i++)
    y[i]=y[i]+a1*x1[i]+a2*x2[i]+a3*x3[i]+a4*x4[i]+a5*x5[i];
) @*/
{
  int i;
  register int cbv_1;
  cbv_1 = N - 5;
#pragma ivdep
#pragma vector always
  for (i = 0; i <= cbv_1; i = i + 5) {
    y[i] = y[i] + a1 * x1[i] + a2 * x2[i] + a3 * x3[i] + a4 * x4[i] + a5 * x5[i];
    y[(i + 1)] = y[(i + 1)] + a1 * x1[(i + 1)] + a2 * x2[(i + 1)] + a3 * x3[(i + 1)] + a4 * x4[(i + 1)] + a5 * x5[(i + 1)];
    y[(i + 2)] = y[(i + 2)] + a1 * x1[(i + 2)] + a2 * x2[(i + 2)] + a3 * x3[(i + 2)] + a4 * x4[(i + 2)] + a5 * x5[(i + 2)];
    y[(i + 3)] = y[(i + 3)] + a1 * x1[(i + 3)] + a2 * x2[(i + 3)] + a3 * x3[(i + 3)] + a4 * x4[(i + 3)] + a5 * x5[(i + 3)];
    y[(i + 4)] = y[(i + 4)] + a1 * x1[(i + 4)] + a2 * x2[(i + 4)] + a3 * x3[(i + 4)] + a4 * x4[(i + 4)] + a5 * x5[(i + 4)];
  }
  register int cbv_2, cbv_3;
  cbv_2 = N - ((N - (0)) % 5);
  cbv_3 = N - 1;
#pragma ivdep
#pragma vector always
  for (i = cbv_2; i <= cbv_3; i = i + 1) 
    y[i] = y[i] + a1 * x1[i] + a2 * x2[i] + a3 * x3[i] + a4 * x4[i] + a5 * x5[i];
}
/*@ end @*/
/*@ end @*/

